FROM node:16-bullseye as build

WORKDIR /app

COPY package*.json ./

RUN npm ci

COPY . .

CMD ["npm", "build"]

FROM nginx:alpine

ADD ./config/defualt.config etc/nginx/config.d/defualt.config
COPY --from=build /dist/app/all-shop /var/www/app/
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]